### ISSUE TITLE
Node agnostic Link To Post URL

### ISSUE THREAD

**Issue by GJARTmusic** [deso-protocol/core#107]
If you use Link To Post on one node the full URL of that node is used. When the post appears on another node the original node URL is shown. This is highly confusing for Users, forcing them to log in to a further node to see the post.

The Link To Post feature needs to be node agnostic so that regardless of where it's originally posted it can be accessed on the same node.

Here is an example of one post with three different URLs

https://nachoaverage.com/posts/8822f3ce68544d58cae46becea81028dec88cc02cc859ab0f79318eb04e629d4?feedTab=Following&tab=posts

https://tijn.club/posts/8822f3ce68544d58cae46becea81028dec88cc02cc859ab0f79318eb04e629d4?feedTab=Following&tab=posts

https://members.giftclout.com/posts/8822f3ce68544d58cae46becea81028dec88cc02cc859ab0f79318eb04e629d4?feedTab=Following&tab=posts

**Comment by maebeam** [comment]
I would suggest that frontends dynamically replace URLs based on certain regexes.
