### ISSUE TITLE
restricted post feature

### ISSUE THREAD

**Issue by mikestaub** [deso-protocol/core#111]
How can a user submit a post that only a select group of users can view? ( not a group DM )

**Comment by tijno** [comment]
This is not possible at the moment and would need updates to core to implement this.

There is a hack/workaround that may help you: the hide parent post trick.

Create a post, 
reply to it with he content and tagging the people you want to see it, 
then hide the parent. 

Of course the replies will still be in the open blockchain - but they wont show on bitclout.com

**Comment by mikestaub** [comment]
That is an interesting hack thanks.

So this social product is replacing Twitter, not Facebook then as it seems to focus on public discourse instead of smaller private groups.

Has anyone solved the GDPR issues yet of blockchain products? If my app allows users to store PII on bitclout's chain, is it enough to mark it as 'hidden' from a legal perspective?

**Comment by tijno** [comment]
You would need to get your own legal advice on that. Im not sure what the position is. 

Note that GDPR is mainly about personal identifiable info like phone, email, ID etc.

As these are not on chain - its definitely a node decision rather then a bitclout one.

The harder one i suspect is the right to be forgotten stuff in the EU. 

No idea how that would interpret a blockchain

**Comment by maebeam** [comment]
Unfortunately this is not possible given how our chain is currently designed. Any private content would need to be stored off chain.

**Comment by mikestaub** [comment]
Thanks for clarifying. That is too bad as it massively limits the use case of the protocol. The only other workaround is to encrypt the posts with a shared key, but then those keys must be managed by all the participants.

**Comment by maebeam** [comment]
@mikestaub if you have ideas on how we might be able to implement this in a reasonable way I'm open to hearing them. I've personally researched most of the options available and none of them are user friendly / scalable enough for us to implement.

I think off chain content could be very normal and acceptable especially for things like token gated access.

**Comment by znmead** [comment]
Check this out from Pearl: https://diamondapp.com/posts/f3e84b2fafc2d71137ef715ce7a4313eb6f0c9666aa45381d53eb4c66125cb8c?feedTab=Hot
