### ISSUE TITLE
Erroraneous BlockHashHex in transaction on blockchain

### ISSUE THREAD

**Issue by starykolarz** [deso-protocol/core#144]
TransactionIDBase58Check: 3JuETNfkcDLas17M1ujVB21bFNhtCeSC9TZSQNDiAYHdHXyNKdi9d9
returns BlockHashHex: 53c7878afa8e50a667934eeb0f5c289c675d409ef0d2dc6e1235af3032a36bb3

This block hash hex doesn't exist when queried via block api. Tried on multiple nodes, including bitclout.com. Submitting as I'm not able to trace myself if this is normal, or it's a sign of some hidden problem?

{
	"TransactionIDBase58Check": "3JuETNfkcDLas17M1ujVB21bFNhtCeSC9TZSQNDiAYHdHXyNKdi9d9",
	"PublicKeyBase58Check":"",
	"IDsOnly":false
}
{
   "Error": "",
   "Transactions": [   {
      "TransactionIDBase58Check": "3JuETNfkcDLas17M1ujVB21bFNhtCeSC9TZSQNDiAYHdHXyNKdi9d9",
      "RawTransactionHex": "1ebe8180bfa2f49b591c145e14baa85cb3d8107247dfd9d093c7f154694c9b22590097d2d38fdf19396fb1a876bcdba1a6fe6f8a47a4a5875b6a85321f29934a5ec40057dae3d3f06f84d2774471f1f25f881e4e8970259e53d117d95fa60902682c8800472ee469ccee6c866c002c67e638e13ed56e9af121483b84cc6ff1bea128af7800ee3aca0fd9f9890b09d28983936bfe6f62341b0ffe860a9e5f46cd5b29a9267a0092fbbba5632c6d0f9a074a6f897b0e74376643c89773b855fb5062227089c7a7006209fd528ca250df4105f39204233361f7dde54466f2889e775e9bc24c884f8300c0b8a9eaba75ad326c817fef7b75b40ec305421cf971a556b98d185abd6c751b00fdd7c226530ce29057bd46430e52caff855bd315f617b5d288779475aa53882000c0a7e8add6b90046ac2d5f0840acde7e4aa9d44fe419bb755c89ad087f3edf280003c62da553cde4610dbefd5326590404fb8ec74e8bb80b122ee3b03acc27ef94015d34f94d235b2f74d11ba020502592c66f33206e307366f475c2af660ed4322f009a56d113846e9c57470352019711bb1aab505c7bafaf623ab01642adc99af49300ccd5c02208c5e49cbe9b061bf69401d4729510b4311ce5de3e5763bcf335b5cd006b61c11d034156ce91d65fc89e68d9e4d06631ff25626125a41061549d4ed10500c800cec11a0e362fa5f48e7f1a33341e6209309ba0ac87ccdb71ade1b5b73c85006937de8ea9954641a42b4294a452fbf8b8ef316831216e808d6ec58f2c2ecbb30018feb978c636c1745370dd03134cc64c31fe96d3a8edc310e4423d02eccc31990026dbdf1dccb2f8d6cf1ddd3580ed5bded43868711fb4c709a400042e574d4796001428a3c0b2e6cd034b701429868e5369d01ec762bfe4b7b22453e55bc56e38c000c3f83ae3a3f605bafd5365dc0561d906d5d1164a7c02ad679c30fe20e3e6f397001f0fa4e81649c152c0f4816fccff6d1b031381abb5cc4d2a8b368760bb7d66db00a376c401f1d9ce4034660029471e58de19c81abde88825cc24aa385175e382b400848d50a2603638a8fcecf20127668c55119f15324e2fd86a6f5170779f4fd058006c2506fbfe78a4b194e6994e80e2d7597e317f9ca31e498246e68515cff468af0023d9070a0fbae99879970681ae99702b2c5a68d5015dec3f57d85a1d90156a49002547a295f9a22cd76429f4b18f4d02d0f08bfbe4fb5d7a57563d21dc793a40ec00b5e22d960f8db881003d36c1b739a0a7a9fae8ada960f3e37ece88e09804e24b006a3af6d13843af263187e227464cb271c62d0ae88c6f3114d0e4087e12bd43e70038dabc5855eca3c56e16e4ac140051daebdbc9b0376a2dd70f4b6bc804c77d460002030633bc2abd496dea2eb42d1076a190df2e524b5dadbaa438679ae9b6254af7aa90b5dad2f601032db0d6fe16086d8650faa600d3dc82b5ec284bdcfcd54a23361596fe3f663be9bfd9859a0b020021032db0d6fe16086d8650faa600d3dc82b5ec284bdcfcd54a23361596fe3f663be900473045022100ca8c0252964d81b89167a633d9c2852034107d7fa2f5e6f81c97b8a3055f542f0220182408d2c43e29264dcb994661a6927106ae010677b3017ae0f35b2c3ea49544",
      "Inputs":       [
                  {
            "TransactionIDBase58Check": "3JuEUBfwHgxQAhjMd4szXYHN8fnPuvsnbNCBeeLhic1CnwRpdxoJxW",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuETtdrAxyEuAfA9DBVQmpuMD1sGr3TfbsSM1u7mpguFGKajpXU9v",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuETQTrnD1vwGGoycr5wRTmUPqSiKNDGPQWKuYsM9TEujkeMbHXsc",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuETH7zsgKj1eoobcELK7YQhxjgtEXMJDtUiPckXxkrTjHoFEQGDx",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuEUYgybWBd835cWQtQSVfnmYwGVr8RLTp2VwrcFXWawa7LNmtvyc",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuETrWDFKx6G5Zh8TbiQU5BJfDLu5bU4vuJHyKixQ6w3pQ8bpe6es",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuETUwzgHhCCaxjwzESD6WPsSaRggjLWTWEqPiaNLHtJbEFuarBHn",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuEUCeXagHEysLS9Dxg4aYT9aLgEzFzZ3qe2Y1oVeTiiiMLZU17BD",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuEUfZnzfe1A6PHmLapPaeipoQyC8oRcqrbUs7jXQyCMT41KDD5wu",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuEUCcrckpF5qMBBuPeWZjvHPPnskoJbPbtxitSo6YgdLVPwEPBub",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuESmS8DUqXoRGGvBgs2DGGcCtrDPPngUrTn5LrvWHnrsmbhtDcG1",
            "Index": 1
         },
                  {
            "TransactionIDBase58Check": "3JuETSpZn49dZmExKcrqiaPbEoxSHyjeZaFjcn3QmD29VQRGr2zKYY",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuETuk76WQ2DWayxnyGp2PHPdoVefDhaUAwMeVz3mvGL5Qdqbi46a",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuEUHyxJKKiwd6REWgRe9gtYMVvaMsrGp1CXoorMHH6pCtT1xazYd",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuETZ4ePBDECtrDdFBbx3giKLHsqXVcgJyBeww6GJPvdfB6SDYLKP",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuEUFrXpXW4C3AWeQ2diMj4iwgr4GNEz4fmrDCp7xbpBTqkbbdK5F",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuETY7NvMAHkrourFz2VozDgYxVU8BoV9suEgDAGy8RsCcKjHwa59",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuESvnBdvPn1HpibAp8nK8xTFPqvoCV1wLiwH1eRsMpjWKr2j6vMS",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuET2tKPJYoFCpymb2qDsvVCxqFt4mkXGKHpSwa5rReirSyVt5P8J",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuESteeYphhH1fWAUcjZ8tgHFGgPmnZvqQk27kA1MD7JFfbZnjvD1",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuEUE5W3uvG57n3gtye5JWcdNuj587VqZ5y7UZezMDbXnhnwztQX5",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuESyT8kMt3pVf8UQrPWuvgWMPj4HjvQWAPiXWm7PyfsZywzPSrqg",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuETymBnGNgLTe5L8qSiHc9Z5LedtqGMaACfWyCsXtwesywAh6FWX",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuETk9anM6Egrd58L7MYRYPphvendsrKS6dKDKRXGtmH8V8Hf1beB",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuETZQ8URACYnnwrkfFiewAVcixmVoC4oUAHpm3PNB6xTAmQhmc6L",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuET1ZQL5JuVVva47kN8RK52NaozYVS56sAHsbLXnE2oxutxAY1t9",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuET2ByySu9naU84obTmKhLSkc4u9osWmjEv57BogNa5YxjQHm6i2",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuEU7sgyr9zrgukcN3sjVjYFsSXGxq5bMF1MJK84sUidZ3gZywrCW",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuETYZEN12et1yLNzqX7yZKL7n2gHQssfyy2KM5WqefZXaB6toAiH",
            "Index": 0
         },
                  {
            "TransactionIDBase58Check": "3JuETAozPd6ijBVWdsMv6P1vATpaHbRCjnhoNsyLjRzbTM4pGGnAKo",
            "Index": 0
         }
      ],
      "Outputs":       [
                  {
            "PublicKeyBase58Check": "BC1YLhfM59gdrgzwwvAw3UgqsGLr442BBwDn2dSBrBR4gJheFWVWrw8",
            "AmountNanos": 66208570000
         },
                  {
            "PublicKeyBase58Check": "BC1YLhxjkv3gZVcrTEdiX7t1ewi56yfJ4LwdSK1QtuiQe8XUeJRj6Vt",
            "AmountNanos": 3007409343
         }
      ],
      "SignatureHex": "3045022100ca8c0252964d81b89167a633d9c2852034107d7fa2f5e6f81c97b8a3055f542f0220182408d2c43e29264dcb994661a6927106ae010677b3017ae0f35b2c3ea49544",
      "TransactionType": "BASIC_TRANSFER",
      "BlockHashHex": "53c7878afa8e50a667934eeb0f5c289c675d409ef0d2dc6e1235af3032a36bb3",
      "TransactionMetadata":       {
         "BlockHashHex": "53c7878afa8e50a667934eeb0f5c289c675d409ef0d2dc6e1235af3032a36bb3",
         "TxnIndexInBlock": 0,
         "TxnType": "BASIC_TRANSFER",
         "TransactorPublicKeyBase58Check": "BC1YLhxjkv3gZVcrTEdiX7t1ewi56yfJ4LwdSK1QtuiQe8XUeJRj6Vt",
         "AffectedPublicKeys":          [
                        {
               "PublicKeyBase58Check": "BC1YLhfM59gdrgzwwvAw3UgqsGLr442BBwDn2dSBrBR4gJheFWVWrw8",
               "Metadata": "BasicTransferOutput"
            },
                        {
               "PublicKeyBase58Check": "BC1YLhxjkv3gZVcrTEdiX7t1ewi56yfJ4LwdSK1QtuiQe8XUeJRj6Vt",
               "Metadata": "BasicTransferOutput"
            }
         ],
         "TxnOutputs":          [
                        {
               "PublicKey": "AwYzvCq9SW3qLrQtEHahkN8uUktdrbqkOGea6bYlSveq",
               "AmountNanos": 66208570000
            },
                        {
               "PublicKey": "Ay2w1v4WCG2GUPqmANPcgrXsKEvc/NVKIzYVlv4/Zjvp",
               "AmountNanos": 3007409343
            }
         ],
         "BasicTransferTxindexMetadata":          {
            "TotalInputNanos": 69215980527,
            "TotalOutputNanos": 69215979343,
            "FeeNanos": 1184,
            "UtxoOpsDump": "",
            "UtxoOps": null,
            "DiamondLevel": 0,
            "PostHashHex": ""
         }
      }
   }],
   "LastTransactionIDBase58Check": "",
   "LastPublicKeyTransactionIndex": 0,
   "BalanceNanos": 0
}

{
	"Height": 0,
	"HashHex": "53c7878afa8e50a667934eeb0f5c289c675d409ef0d2dc6e1235af3032a36bb3",
	"FullBlock": false
}

{"Error": "APIBlockRequest: Problem fetching block: Key not found"}

**Comment by tijno** [comment]
This is genesis block - theres an issue in chain that i posted about back in March. Let me find the issue

**Comment by tijno** [comment]
https://github.com/deso-protocol/core/issues/46

**Comment by starykolarz** [comment]
Thanks!  I looked throught the titles for duplicates, but genesis didn't ring a bell :-(

**Comment by maebeam** [comment]
Yes apologies this is still an issue with TXIndex. I deprioritized fixing it because TXIndex is deprecated. Closing in favor of #46
