### ISSUE TITLE
Third party packages

### ISSUE THREAD

**Issue by hz61p1** [deso-protocol/core#155]
I probably don't know any nuances, but I can't just take and import your kernel into the project because of modified third-party packages. I have to clone the repository and take it to a level above the project.
In go.mod to register ...
```
replace github.com/deso-protocol/core => ../core/
replace github.com/golang/glog => ../core/third_party/github.com/golang/glog
replace github.com/laser/go-merkle-tree => ../core/third_party/github.com/laser/go-merkle-tree
replace github.com/sasha-s/go-deadlock => ../core/third_party/github.com/sasha-s/go-deadlock
```
Can you give any recommendations for development? Perhaps it is worth considering the design in the form of full-fledged modules in separate repositories and pull up as dependencies?

**Comment by maebeam** [comment]
Thanks for bringing this up, I've been meaning to fix this for a while
