### ISSUE TITLE
api/v1/block no longer returns TransactionMetadata 

### ISSUE THREAD

**Issue by oO** [deso-protocol/core#175]
It looks like the recent changes for the DAO coin introduced a bug and the Transaction no longer contain Metadata

`"TransactionMetadata": {
      "BlockHashHex": "",
      "TxnIndexInBlock": 0,
      "TxnType": "",
      "TransactorPublicKeyBase58Check": "",
      "AffectedPublicKeys": null,
      "TxnOutputs": null
    }`

**Comment by diamondhands0** [comment]
Looking into this now. Thanks for reporting it!

**Comment by diamondhands0** [comment]
@oO can you please include your full request as a curl command? Note that block rewards don't have transaction metadata.

**Comment by oO** [comment]
I reverted to 3 commits back so I no longer have it, but it's essentially POST /api/v1/block { Height:94920, FullBlock: true } 
every single transactions returned had an empty TransactionMetadata object.

( and also BLOCK_REWARDS do have a Metadata Block )

```
    "TransactionMetadata": {
      "BlockHashHex": "0000000000005790e7b043b653b44868a62913ffe410b66e66560e5408678da9",
      "TxnIndexInBlock": 0,
      "TxnType": "BLOCK_REWARD",
      "TransactorPublicKeyBase58Check": "8mkU8yaVLs",
      "AffectedPublicKeys": [
        {
          "PublicKeyBase58Check": "BC1YLhGdJHfi6qWhuvxyQQqXU3dENb812oQC5PdLoyM6MQsdmScnTn2",
          "Metadata": "BasicTransferOutput"
        }
      ],
```

**Comment by diamondhands0** [comment]
@oO are you still experiencing this issue?

**Comment by oO** [comment]
No longer an issue. Close
