### ISSUE TITLE
security@deso.org does not exist. 

### ISSUE THREAD

**Issue by namelessperson0** [deso-protocol/core#205]
The email security@deso.org does not exist. 
Sending email to that address results in error. 
That email is mentioned in https://docs.deso.org/devs/bug-bounty

**Comment by iPaulPro** [comment]
![bill-hicks-mic-tap](https://user-images.githubusercontent.com/354227/152450599-466b9270-5a26-4b31-ab2f-69988094f5b5.gif)

**Comment by diamondhands0** [comment]
This was due to a transition from a different domain to deso.org (i.e. a bad find and replace). We've put in node.admin+security@deso.org for now, and will update with a new security@deso.org email shortly.
