### ISSUE TITLE
Get buy now bid transaction from Postgres DB

### ISSUE THREAD

**Issue by mvanhalen** [deso-protocol/core#225]
When completing a buy bow bid transaction all works fine. Except to get the transaction data from Postgres. I was assuming it would end up in pg_metadata_accept_nft_bids but it´s not. 

I made a buy now bid transaction (3JuEU8F7ZRuUWxEJYPUnEuVRceA4mLZKXyTL1435H8ff2Vkqe5GWBm) today for nft 13553654e884d955e9e6462244720e39d97a521a20a49c411974c7ec3b9942e7

`select * from pg_metadata_accept_nft_bids where nft_post_hash = decode('13553654e884d955e9e6462244720e39d97a521a20a49c411974c7ec3b9942e7','hex')
`
Is empty. Ok not so weird

`select * from pg_metadata_nft_bids where nft_post_hash = decode('13553654e884d955e9e6462244720e39d97a521a20a49c411974c7ec3b9942e7','hex')
`
Is not empty, but no easy way to see if accepted or not. Or it it was buy now. 
`select * from pg_nft_bids where nft_post_hash = decode('13553654e884d955e9e6462244720e39d97a521a20a49c411974c7ec3b9942e7','hex')
`
Empty again. That is a bit odd I think

In pg_metadata_create_nft table there is no buy now info either. And the NFT get´s reset after sale.

Kinda think this data should be easier available. But not sure if another table is needed or just include in pg_metadata_accept_nft_bids  with a isbuynow boolean?

Let me know your thoughts @diamondhands0 @lazynina  right now NFTz is under reporting NFT sales (:. Can create a separate table if needed. But would like to know if this behavior is correct.

**Comment by lazynina** [comment]
@mvanhalen - there is some code missing to support adding to the accepted_nft_bids table in postgres.go. We need to check if a bid is a bid on a buy now NFT that exceeds the buy now price and if so, adds to `metadataAccepteNFTBids`. I would welcome a PR that appends to this slice around line 1077 in postgres.go

**Comment by mvanhalen** [comment]
> @mvanhalen - there is some code missing to support adding to the accepted_nft_bids table in postgres.go. We need to check if a bid is a bid on a buy now NFT that exceeds the buy now price and if so, adds to `metadataAccepteNFTBids`. I would welcome a PR that appends to this slice around line 1077 in postgres.go

Thanks for the quick follow up. Will try to beef up my go skills and make an attempt

**Comment by mvanhalen** [comment]
Added a PR #226 . It compiles, but not sure if I´m doing it right. If you think it´s Ok I´ll setup a sync to check it.

**Comment by lazynina** [comment]
#226 is exactly what I was suggesting. I'm not positive it's right. I believe the NFT entry should still reflect the buy now price, but I'm not positive. Basically it's a question of ordering the transaction.

It may be faster to just run a regtest node locally (run the n0_test script with a postgres URI) and then generate some buy now transactions locally

**Comment by mvanhalen** [comment]
Ok will run a test tomorrow and let you know. Will check the NFT entry thing. To avoid an extra postgres call.

**Comment by lazynina** [comment]
I've run a test locally and #226 works as expected - just had to set UnlockableText to an empty byte slice! 226 has been merged with that change.
