### ISSUE TITLE
PG crash block 108731 `RuleErrorCreateProfileTxnOutputExceedsInput`

### ISSUE THREAD

**Issue by tijno** [deso-protocol/core#234]
I mentioned this in #230 but I think this is probably a new issue.

My PG was running 2.0.5 syncing fine upto last night when 108731 was mined. It crashed. Updating to new stable this morning (2.0.7) its still stuck at 108731 with this error:

I guess `RuleErrorCreateProfileTxnOutputExceedsInput` triggered by updateProfile [here](https://github.com/deso-protocol/core/blob/main/lib/block_view_profile.go#L648)

> I0303 09:35:18.084262       1 server.go:1147] Server._handleBlock: Received block ( 108741 / 108896 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=3 ]
> E0303 09:35:18.195247       1 verify.go:1129] SetJumioUSDCents: invalid bytes read: 0
> E0303 09:35:18.195273       1 verify.go:1147] SetJumioKickbackUSDCents: invalid bytes read: 0
> E0303 09:35:18.204038       1 blockchain.go:1214] MarkBlockInvalid: Block height: 108741, Block hash: 00000000000014b98e050080d584625a69236b78775bb3792827f9351b9d0eb7, Error: ConnectBlock: : ConnectTransaction: : RuleErrorCreateProfileTxnOutputExceedsInput
> E0303 09:35:18.204073       1 blockchain.go:1215] MarkBlockInvalid: Printing stack trace so error is easy to find: 
> E0303 09:35:18.204105       1 blockchain.go:1216] goroutine 54 [running]:
> runtime/debug.Stack()
>         /usr/lib/go/src/runtime/debug/stack.go:24 +0x65
> github.com/deso-protocol/core/lib.(*Blockchain).MarkBlockInvalid(0xc0060871d0, 0xc0016dc3c0, {0xc0060b4c00, 0x51})
>         /deso/src/core/lib/blockchain.go:1216 +0x14a
> github.com/deso-protocol/core/lib.(*Blockchain).ProcessBlock(0xc0000fcf20, 0xc04fa35770, 0xc5)
>         /deso/src/core/lib/blockchain.go:1917 +0x1fa5
> github.com/deso-protocol/core/lib.(*Server)._handleBlock(0xc0008fe000, 0xc005fca6c0, 0xc04fa35770)
>         /deso/src/core/lib/server.go:1202 +0x4e5
> github.com/deso-protocol/core/lib.(*Server)._handlePeerMessages(0xf4241, 0x0)
>         /deso/src/core/lib/server.go:1494 +0x18d
> github.com/deso-protocol/core/lib.(*Server).messageHandler(0xc0008fe000)
>         /deso/src/core/lib/server.go:1534 +0x19c
> created by github.com/deso-protocol/core/lib.(*Server).Start

Theres only 1 update profile tx in that block: [3JuEThCT3ToRkR4RUVkdxTX6QAYyegY7WsB2ujzrUVq5Focq3LTZfD](https://explorer.deso.org/?query-node=https:%2F%2Fnode.deso.org&transaction-id=3JuEThCT3ToRkR4RUVkdxTX6QAYyegY7WsB2ujzrUVq5Focq3LTZfD)

Fees on the Tx seem fine though.

```json
"BasicTransferTxindexMetadata": {
    "TotalInputNanos": 49512,
    "TotalOutputNanos": 46186,
    "FeeNanos": 3326,
```

I dont think resync was required for PG when going from 2.0.5 to 2.0.7 - but please confirm if thats the cause.

cc @lazynina

**Comment by lazynina** [comment]
@tijno - Currently syncing a postgres node and will let you know what I find.

**Comment by tijno** [comment]
@lazynina did you hit the same issue or is it just my node that has it?

@mvanhalen how are things on your end?

**Comment by mvanhalen** [comment]
> @lazynina did you hit the same issue or is it just my node that has it?
> 
> @mvanhalen how are things on your end?

Did not even get to that point. Created an issue #237 hit a mem error earlier. Kind of busy with NFTz stuff because of the new version. Will try to debug later today.

**Comment by tijno** [comment]
Same for me. Stuck at issue block 99415 as per #237

**Comment by tijno** [comment]
Looks like this is not an issue with a clean sync so closing. But had to solve #237 to get this far.
