### ISSUE TITLE
Postgres sync crashes on block 99415 

### ISSUE THREAD

**Issue by mvanhalen** [deso-protocol/core#237]
Postgres sync of latest build stops on block 99415 and keeps restarting. With fresh sync. Probably some nil value. Will debug

`I0305 08:07:47.297285       1 server.go:1147] Server._handleBlock: Received block ( 99415 / 109439 ) from Peer [ Remote Address: 34.123.41.111:17000 PeerID=2 ]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb26d7e]

goroutine 64 [running]:
github.com/go-pg/pg/v10.(*Tx).RunInTransaction.func1()
        /root/go/pkg/mod/github.com/go-pg/pg/v10@v10.10.0/tx.go:91 +0x86
panic({0x10b9580, 0x1eaa660})
        /usr/lib/go/src/runtime/panic.go:1038 +0x215
github.com/deso-protocol/core/lib.(*Postgres).InsertTransactionsTx(0xc0017114b8,0xc0017114c8, {0xc0053de800, 0xb7, 0xc006142660}, 0xc009163540)
        /deso/src/core/lib/postgres.go:1119 +0x1c1e
github.com/deso-protocol/core/lib.(*Postgres).UpsertBlockAndTransactions.func1(0x0)
        /deso/src/core/lib/postgres.go:1353 +0x98
github.com/go-pg/pg/v10.(*Tx).RunInTransaction(0xc005bf8580, {0x17493e8, 0xc00003a290}, 0xc0054e9f80)
        /root/go/pkg/mod/github.com/go-pg/pg/v10@v10.10.0/tx.go:95 +0xa5
github.com/go-pg/pg/v10.(*baseDB).RunInTransaction(0xc0053e3f68, {0x17493e8, 0xc00003a290}, 0xc001b0dc20)
        /root/go/pkg/mod/github.com/go-pg/pg/v10@v10.10.0/tx.go:74 +0x51
github.com/deso-protocol/core/lib.(*Postgres).UpsertBlockAndTransactions(0xc00540a2d0, 0xc001b0dc20, 0xc0056f6000)
        /deso/src/core/lib/postgres.go:1341 +0x5c`

**Comment by tijno** [comment]
Im rerunning full sync to try and see if I hit this issue

**Comment by tijno** [comment]
Yes same issue @mvanhalen 

Using latest hot fix 2.0.7

cc @lazynina

**Comment by mvanhalen** [comment]
@tijno made this change as well and it´s syncing again. Will let you know if I get a full sync. I think the postgres.GetNFT might work because of the sequence of insertion? We do check that value for nil. But it might skip the buy now acceptbid transaction insert indeed.

Was offline for a couple of days needed to watch my health. But going in the right direction again.

**Comment by mvanhalen** [comment]
Fully synced now and over 3000+ accept bid transactions for buy now added. Wonder how much tnx would be missed if any. NFTz stats update coming in hot. So this works @tijno

**Comment by tijno** [comment]
@diamondhands0 @lazynina any thoughts about the above fix?

I know your head down getting fork & daodao done no doubt - but this issue will just prevent future updates from working with postgres.

**Comment by lazynina** [comment]
> @diamondhands0 @lazynina any thoughts about the above fix?
> 
> I know your head down getting fork & daodao done no doubt - but this issue will just prevent future updates from working with postgres.

@tijno - apologies for the delay in getting back to you. Using `NewPKID` isn't always accurate. A PKID will change if a user has had their identity swapped. I think the solution is:
1. If user has a profile, use the PKID from the profile
2. Else, use NewPKID

I'll whip up a PR shortly.

**Comment by lazynina** [comment]
@tijno - [this PR](https://github.com/deso-protocol/core/pull/262) will apply the logic I described above.

**Comment by lazynina** [comment]
> 

regarding your wider concerns about postgres handling transactions in the same block -- I think we need to update the `Preload` function in block_view.go to get all the information we need. I'm a little swamped today, but I'll try to investigate further as soon as I have time.

**Comment by tijno** [comment]
thx @lazynina ive passed the block  with the issue so cant test on the current sync but will try and replicate on maybe testnet if i can get blocks to slow

**Comment by mvanhalen** [comment]
Running a new fresh sync with the #262 PR. @lazynina  and @tijno will let you know when it´s completes.

**Comment by mvanhalen** [comment]
Fully synced without issues. @lazynina @tijno

**Comment by lazynina** [comment]
@mvanhalen - closing since issue is resolved now that #262 is merged
