### ISSUE TITLE
Do not reuse old node Id's

### ISSUE THREAD

**Issue by erwin-willems** [deso-protocol/core#373]
See: https://github.com/deso-protocol/core/commit/c8a0a4c129a8d571f932373620d13458f7a0e310, you should not reuse old node id's. It's confusing with old posts that were already tagged with that old node id..

Just don't do that in the future..

**Comment by chafreaky** [comment]
It was a placeholder name - see PR https://github.com/deso-protocol/core/pull/359 for context

**Comment by erwin-willems** [comment]
Ok, thanks for clarifying
