### ISSUE TITLE
Buy/Sell Number of Clouts lost in txn??

### ISSUE THREAD

**Issue by morphers82** [deso-protocol/core#42]
So I did a test.

I sold all of my coin = 11.539803943 
Then I rebought with exactly 1.85 CLOUT
Then I resold all of my coin(11.539803943) 

After reselling, my wallet balance went down exactly 0.000370487 CLOUT
I did this several times to verify

( rebought to not have a rugpull)

Is this supposed to happen?  I know about transaction fees, 
but I don't think they are supposed to add up between a buy+sell to  0.000370487 CLOUT?

**Comment by maebeam** [comment]
This is expected behavior. There is a very small additional fee for every creator coin transaction to guarantee no money can be printed.
