### ISSUE TITLE
Postgres stops sycning at block 205527

### ISSUE THREAD

**Issue by mvanhalen** [deso-protocol/core#471]
Postgres sync stops at block 205527

The error is:

`
Error while processing block: : ProcessBlock: Problem upserting block and transactions: ERROR #23505 duplicate key value violates unique constraint "pg_metadata_create_post_association_pkey"
E0207 17:04:21.213764       1 peer.go:1220] ReadDeSoMessage: : ReadMessage: Could not read payload for message type (BLOCK): read tcp 172.24.0.4:53252->35.232.92.5:17000: use of closed network connection

Extra info
1 server.go:1749] Server._handleBlock: Received block ( 205527 / 205534 ) from Peer [ Remote Address: 34.123.41.111:17000 PeerID=34 ]
I0207 16:47:28.506673       1 blockchain.go:1914] Node is not fully processed - current statuses are: HEADER_VALIDATED | BLOCK_PROCESSED | BLOCK_STORED | BLOCK_VALIDATED
E0207 16:47:28.506701       1 server.go:1743] Server._handleBlock: Encountered an error processing block <Header: < 205527, 0000000000006ad2675af07fc6b0c1e1ccb015bbec7ff9c580f60e9840a707ed, 1 >, Signer Key: BC1YLh768bVj2R3QpSiduxcvn7ipxF3L3XHsabZYtCGtsinUnNrZvNN>. Disconnecting from peer [ Remote Address: 34.123.41.111:17000 PeerID=34 ]: Error while processing block: : RuleErrorBlockAlreadyExists
E0207 16:47:28.506803       1 peer.go:1220] ReadDeSoMessage: : ReadMessage: Could not read payload for message type (BLOCK): read tcp172.24.0.4:51038->34.123.41.111:17000: use of closed network connection
`

@lazynina @AeonSw4n 

Meaning nftz.me NFT stats will be out of sync

**Comment by lazynina** [comment]
@mvanhalen - we found identified the issue and will be pushing out a fix shortly. Apologies for the inconvenience.

**Comment by AeonSw4n** [comment]
Fixed in #472

**Comment by lazynina** [comment]
@mvanhalen - we found some duplicated inserts into postgres that must have arose after resolving some merge conflicts between associations and access groups. This has been resolved with #472 

I'll cut a new release of core and backend shortly that includes these fixes and then you'll be able to continue syncing with the latest stable image.

**Comment by mvanhalen** [comment]
Thanks @lazynina and @AeonSw4n for the fast follow up. Will wait for the new build and apply it.

**Comment by lazynina** [comment]
Hi @mvanhalen. I've cut new releases with the fixes. can you please try syncing with release v3.1.2? Here's the [core](https://github.com/deso-protocol/core/releases/tag/v3.1.2) and [backend](https://github.com/deso-protocol/backend/releases/tag/v3.1.2) releases for your reference.

Once you get past this block, I'll go ahead and close this issue. thanks for bringing this to our attention.

**Comment by mvanhalen** [comment]
It´s working! Great and fast follow up. Appreciatie it. At block 205550 now. Same as our transaction node. Thanks @lazynina @AeonSw4n @mattfoley8
