### ISSUE TITLE
Recommendations for Bitclout Localization

### ISSUE THREAD

**Issue by ghost** [deso-protocol/core#52]
Currently, the vast majority of users who use Bitclout.com speak English. But in the coming months, millions of people who don't speak English will start hearing about Bitclout. But most people will stop using the site because of the Language barrier. I have suggestions for this problem.
- Bitclout Node setup should be very simple. (Youtube support videos should increase: how do I set up a bitclout node? How do I change the node language?)
- Must be a local stream (country and local language)-The simplest solution for this local stream is:

---Users should be able to choose the country they live in and the language they speak when becoming a member. In this way, the posts of these users can be sent to the local stream very easily.

@maebeam @lazynina @diamondhands0

**Comment by sungkhum** [comment]
Yes, please! How can we help?

**Comment by maebeam** [comment]
For now we recommend users translate the frontend of the app. Now that posts have node sources on them it should be easy for a node operator to only show posts from certain sources.
