### ISSUE TITLE
We need a mechanism to block all direct messages from anyone we don’t follow on the platform just like Twitter offers since the entire BitClout platform is mostly scam bots 🤖

### ISSUE THREAD

**Issue by Barnacules** [deso-protocol/core#53]
![image](https://user-images.githubusercontent.com/8484226/124448444-5097d680-dd37-11eb-876d-2e61051b77f3.jpeg)

![image](https://user-images.githubusercontent.com/8484226/124448590-79b86700-dd37-11eb-9bf5-6a2bebd86938.jpeg)

**Comment by CoderDrShen** [comment]
Yes. Bots are starting to be a huge problem for this platform. I hope the developer team will fix this issue very soon. You can use these settings to get rid of these bot accounts.
![2021-07-05 16_33_29-Window](https://user-images.githubusercontent.com/86081358/124479509-08b49600-ddaf-11eb-810f-d4000c5392d5.png)

**Comment by maebeam** [comment]
For now we recommend you only show holders, holdings, followers, following, etc.

**Comment by namelessperson0** [comment]
Spam issue can be solved by cryptocurrency incentives instead of methods adopted by twitter

**Comment by maebeam** [comment]
This is solved in the frontend for now. We are prioritizing storing blocks on chain.
