### ISSUE TITLE
Move TXIndex to Postgres

### ISSUE THREAD

**Issue by maebeam** [deso-protocol/core#57]

**Comment by tijno** [comment]
@maebeam I noted you mentioned migration to postgresql is progressing and only a few weeks away

https://github.com/bitclout/frontend/issues/370#issuecomment-894566143

What would be the right time to start trying to run a test node based on postgresql (initially on testnet i guess) - to get familiar and figure out best way to move existing nodes & tools across to this new setup?

**Comment by maebeam** [comment]
@tijno It is almost time. I will be merging some of the postgres code very soon!

**Comment by tijno** [comment]
Thx @maebeam  So can i test it with the right branches on core and backend ? On main net or just test net ?

**Comment by maebeam** [comment]
They're not ready for either yet. When they get merged you can start testing with both.

**Comment by mvanhalen** [comment]
This would make it possible to host the progress db (or tindex data) outside the node? Maybe one of the most important updates for node owners. So really looking forward to this. Would it also be possible to make a wrapper for SQL Azure? That would need to be in Go like the mongo db wrapper?

**Comment by maebeam** [comment]
> This would make it possible to host the progress db (or tindex data) outside the node? Maybe one of the most important updates for node owners.

Correct, we're very excited about this.

> Would it also be possible to make a wrapper for SQL Azure? That would need to be in Go like the mongo db wrapper?

I'm using `go-pg` which only supports postgres. It would be not too much effort to migrate to `bun` which could support different SQL backends down the line.

**Comment by mvanhalen** [comment]
Thanks @maebeam that is very exiting indeed. Also making the data available for (easy) usage outside the node. For instance a web app or service ([checkbitclout.com](checkbitclout.com) shameless plug). If you need assistance with a SQL wrapper for Azure I would be available. In the meantime I´ll device into progress db options for azure and the packages you mention.

**Comment by maebeam** [comment]
We no longer plan to move txindex to postgres.
