### ISSUE TITLE
Postgres node hangs on block 293635

### ISSUE THREAD

**Issue by mvanhalen** [deso-protocol/core#880]
We have an issue since with Postgres it hangs on block 293635 showing below error. Restart with latest does not resolve it.

`E1218 19:12:58.551519       1 blockchain.go:1386] MarkBlockInvalid: Block height: 293358, Block hash: 00000000000028d88701f5f4f3383d76dc78cafa1bfd80976f507d837943220e, Error: ConnectBlock: error connecting txn #1: ConnectTransaction: Nonce DeSoNonce: ExpirationBlockHeight: 293635, PartialID: 14327744155825208032 has already been used for PKID &[2 6 103 168 59 161 179 22 84 107 209 70 64 119 9 238 181 233 145 18 52 89 129 9 137 49 28 42 117 184 128 28 147]: RuleErrorReusedNonce`

Seems like something is going wrong. Stats are out of sync on https://nftz.me

@lazynina or @AeonSw4n can you confirm?

Thanks

**Comment by StarGeezerPhil** [comment]
@mvanhalen I'm assuming you've restarted the node already, but sorry - this might be isolated to you.

I've not updated my images in a while (at least a month, maybe two) - so if you're running a newer build that might be worth investigating.

Mines past this point - stalled on 293,926, but like I said on-chain and you'll have seen from the telegram channel - I experience frequent stalls or hangs with the pg node, so these occurrences are common. Usually a few restarts of the image (or a server reboot) seems to clear it... but this means it can never be considered reliably synced (thankfully this is not a production node for end-users).

**Comment by mvanhalen** [comment]
We synced again passed these values. Almost fully in sync again. @StarGeezerPhil to improve the performance of syncing after +200K. We added this index to keep syncing at good speeds. But @lazynina would be looking into improving the query as well.

`CREATE INDEX IF NOT EXISTS index_tx_outputs_key_type_height
    ON [public.pg](http://public.pg/)_transaction_outputs USING btree
    (public_key ASC NULLS LAST, height DESC NULLS FIRST)
    TABLESPACE pg_default;`
